import type { Metadata } from "next";
import MainHeaderComponent from "@/components/main-header";
import { ReactQueryProvider } from "@/components/ReactQueryProvider";
import "./globals.css";



export const metadata: Metadata = {
  title: "Tanstack Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;

}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
         <MainHeaderComponent/>
          {children}
          </ReactQueryProvider>
      </body>
    </html>
  );
}
